# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created: Sat Oct 24 21:51:55 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 611, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(610, 0, 201, 551))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtGui.QToolBox(self.gridLayoutWidget_2)
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 197, 405))
        self.page.setObjectName("page")
        self.toolButton = QtGui.QToolButton(self.page)
        self.toolButton.setGeometry(QtCore.QRect(70, 20, 51, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("square.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(50, 50))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtGui.QToolButton(self.page)
        self.toolButton_2.setGeometry(QtCore.QRect(70, 90, 51, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("circle.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtGui.QToolButton(self.page)
        self.toolButton_3.setGeometry(QtCore.QRect(70, 160, 51, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("triangle.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 197, 405))
        self.page_2.setObjectName("page_2")
        self.toolButton4 = QtGui.QToolButton(self.page_2)
        self.toolButton4.setGeometry(QtCore.QRect(20, 30, 31, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("red.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton4.setIcon(icon3)
        self.toolButton4.setIconSize(QtCore.QSize(25, 25))
        self.toolButton4.setObjectName("toolButton4")
        self.toolButton_5 = QtGui.QToolButton(self.page_2)
        self.toolButton_5.setGeometry(QtCore.QRect(80, 30, 31, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("orange.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon4)
        self.toolButton_5.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtGui.QToolButton(self.page_2)
        self.toolButton_6.setGeometry(QtCore.QRect(140, 30, 31, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("yellow.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon5)
        self.toolButton_6.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_9 = QtGui.QToolButton(self.page_2)
        self.toolButton_9.setGeometry(QtCore.QRect(20, 90, 31, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("greenLight.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon6)
        self.toolButton_9.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_7 = QtGui.QToolButton(self.page_2)
        self.toolButton_7.setGeometry(QtCore.QRect(80, 90, 31, 31))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("greenDark.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon7)
        self.toolButton_7.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtGui.QToolButton(self.page_2)
        self.toolButton_8.setGeometry(QtCore.QRect(140, 90, 31, 31))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("blueDark.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon8)
        self.toolButton_8.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_10 = QtGui.QToolButton(self.page_2)
        self.toolButton_10.setGeometry(QtCore.QRect(20, 140, 31, 31))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("blueLight.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_10.setIcon(icon9)
        self.toolButton_10.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_10.setObjectName("toolButton_10")
        self.toolButton_11 = QtGui.QToolButton(self.page_2)
        self.toolButton_11.setGeometry(QtCore.QRect(80, 140, 31, 31))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("purpleLight.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_11.setIcon(icon10)
        self.toolButton_11.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_11.setObjectName("toolButton_11")
        self.toolButton_12 = QtGui.QToolButton(self.page_2)
        self.toolButton_12.setGeometry(QtCore.QRect(140, 140, 31, 31))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("pink.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_12.setIcon(icon11)
        self.toolButton_12.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_12.setObjectName("toolButton_12")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 197, 405))
        self.page_3.setObjectName("page_3")
        self.horizontalSlider = QtGui.QSlider(self.page_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 60, 160, 21))
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = QtGui.QSlider(self.page_3)
        self.verticalSlider.setGeometry(QtCore.QRect(90, 140, 21, 160))
        self.verticalSlider.setSliderPosition(50)
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.verticalSlider.setTickInterval(10)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label = QtGui.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(20, 80, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(170, 80, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(60, 290, 20, 16))
        self.label_4.setObjectName("label_4")
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton4.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_9.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_7.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_8.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_10.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_11.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_12.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "   0", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

